apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-config
  namespace: default
data:
  main.tf: |
    terraform {
      backend "local" {
        path = "terraform.tfstate"
      }
      required_providers {
        solacebroker = {
          source  = "SolaceProducts/solacebroker"
          version = "1.1.0"
        }
      }
    }

    provider "solacebroker" {
      username = "admin"
      password = "xvPuymxlJ2"
      url      = "http://192.168.0.192:8080"
    }

    resource "solacebroker_msg_vpn" "test" {
      msg_vpn_name        = "new-3"
      enabled             = true
      max_msg_spool_usage = 10
    }

    resource "solacebroker_msg_vpn_queue" "q" {
      msg_vpn_name    = solacebroker_msg_vpn.test.msg_vpn_name
      queue_name      = "green"
      ingress_enabled = true
      egress_enabled  = true
    }
