apiVersion: batch/v1
kind: Job
metadata:
  name: solace-terraform-job
spec:
  template:
    spec:
      containers:
      - name: terraform
        image: hashicorp/terraform:1.0.0
        workingDir: /workspace
        command: ["/bin/sh", "-c"]
        args:
        - |
          terraform init
          terraform apply -auto-approve
        volumeMounts:
        - name: terraform-config
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: terraform-config
        configMap:
          name: terraform-config
