apiVersion: batch/v1
kind: Job
metadata:
  generateName: solace-terraform-job-
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  template:
    spec:
      initContainers:
      - name: copy-terraform-files
        image: alpine:3.14
        command: ['sh', '-c']
        args:
        - cp /config/* /workspace/
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: workspace
          mountPath: /workspace
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        workingDir: /workspace
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          terraform init
          terraform plan -out=tfplan
          terraform show -no-color tfplan
          terraform apply -auto-approve tfplan
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: terraform-state
          mountPath: /terraform-state
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: terraform-config
      - name: workspace
        emptyDir: {}
      - name: terraform-state
        persistentVolumeClaim:
          claimName: terraform-state-pvc
