apiVersion: batch/v1
kind: Job
metadata:
  name: solace-terraform-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        workingDir: /workspace
        command: ["/bin/sh", "-c"]
        args:
        - |
          terraform init
          terraform apply -auto-approve
        volumeMounts:
        - name: terraform-config
          mountPath: /workspace
          readOnly: true
        - name: terraform-state
          mountPath: /workspace/terraform.tfstate.d
      restartPolicy: Never
      volumes:
      - name: terraform-config
        configMap:
          name: terraform-config
      - name: terraform-state
        persistentVolumeClaim:
          claimName: terraform-state-pvc
