apiVersion: batch/v1
kind: Job
metadata:
  generateName: solace-terraform-job-
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        workingDir: /workspace
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          terraform init
          terraform plan -out=tfplan
          terraform show -no-color tfplan
          terraform apply -auto-approve tfplan
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
        - name: terraform-state
          mountPath: /workspace/state
      restartPolicy: Never
      volumes:
      - name: workspace-volume
        emptyDir: {}
      - name: terraform-state
        persistentVolumeClaim:
          claimName: terraform-state-pvc
