apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-state-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi